/*
 * This source file was generated by the Gradle 'init' task
 */
package parcial3;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    private final static Logger logger = LogManager.getLogger(App.class);

    public static void main(String[] args) {
        logger.info("saludo");
        System.out.println(new App().getGreeting());
        logger.info("fin del saludo");
    }
}
